# Generated by Django 3.1 on 2025-03-14 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pro_img',
            field=models.ImageField(blank=True, upload_to='photos/products'),
        ),
    ]
